# Type stubs for centaur_technical_indicators.candle_indicators
# Auto-generated from the Rust binding signatures; keep in sync with src/candle_indicators.rs.

class single:
    @staticmethod
    def donchian_channels(high: list[float], low: list[float]) -> tuple[float, float, float]: ...
    @staticmethod
    def ichimoku_cloud(highs: list[float], lows: list[float], close: list[float], conversion_period: int, base_period: int, span_b_period: int) -> tuple[float, float, float, float, float]: ...
    @staticmethod
    def keltner_channel(high: list[float], low: list[float], close: list[float], constant_model_type: str, atr_constant_model_type: str, multiplier: float) -> tuple[float, float, float]: ...
    @staticmethod
    def mcginley_dynamic_bands(prices: list[float], deviation_model: str, deviation_multiplier: float, previous_mcginley_dynamic: float) -> tuple[float, float, float]: ...
    @staticmethod
    def mcginley_dynamic_envelopes(prices: list[float], difference: float, previous_mcginley_dynamic: float) -> tuple[float, float, float]: ...
    @staticmethod
    def moving_constant_bands(prices: list[float], constant_model_type: str, deviation_model: str, deviation_multiplier: float) -> tuple[float, float, float]: ...
    @staticmethod
    def moving_constant_envelopes(prices: list[float], constant_model_type: str, difference: float) -> tuple[float, float, float]: ...
    @staticmethod
    def supertrend(high: list[float], low: list[float], close: list[float], constant_model_type: str, multiplier: float) -> float: ...

class bulk:
    @staticmethod
    def donchian_channels(high: list[float], low: list[float], period: int) -> list[tuple[float, float, float]]: ...
    @staticmethod
    def ichimoku_cloud(highs: list[float], lows: list[float], close: list[float], conversion_period: int, base_period: int, span_b_period: int) -> list[tuple[float, float, float, float, float]]: ...
    @staticmethod
    def keltner_channel(high: list[float], low: list[float], close: list[float], constant_model_type: str, atr_constant_model_type: str, multiplier: float, period: int) -> list[tuple[float, float, float]]: ...
    @staticmethod
    def mcginley_dynamic_bands(prices: list[float], deviation_model: str, deviation_multiplier: float, previous_mcginley_dynamic: float, period: int) -> list[tuple[float, float, float]]: ...
    @staticmethod
    def mcginley_dynamic_envelopes(prices: list[float], difference: float, previous_mcginley_dynamic: float, period: int) -> list[tuple[float, float, float]]: ...
    @staticmethod
    def moving_constant_bands(prices: list[float], constant_model_type: str, deviation_model: str, deviation_multiplier: float, period: int) -> list[tuple[float, float, float]]: ...
    @staticmethod
    def moving_constant_envelopes(prices: list[float], constant_model_type: str, difference: float, period: int) -> list[tuple[float, float, float]]: ...
    @staticmethod
    def supertrend(high: list[float], low: list[float], close: list[float], constant_model_type: str, multiplier: float, period: int) -> list[float]: ...

