# Type stubs for centaur_technical_indicators.chart_trends
# Auto-generated from the Rust binding signatures; keep in sync with src/chart_trends.rs.

def break_down_trends(prices: list[float], max_outliers: int, soft_adj_r_squared_minimum: float, hard_adj_r_squared_minimum: float, soft_rmse_multiplier: float, hard_rmse_multiplier: float, soft_durbin_watson_min: float, soft_durbin_watson_max: float, hard_durbin_watson_min: float, hard_durbin_watson_max: float) -> list[tuple[int, int, float, float]]: ...
def overall_trend(prices: list[float]) -> tuple[float, float]: ...
def peak_favorable_move(prices: list[float], index: int, period: int) -> float: ...
def peak_trend(prices: list[float], period: int) -> tuple[float, float]: ...
def peaks(prices: list[float], period: int, closest_neighbor: int) -> list[tuple[float, int]]: ...
def valley_favorable_move(prices: list[float], index: int, period: int) -> float: ...
def valley_trend(prices: list[float], period: int) -> tuple[float, float]: ...
def valleys(prices: list[float], period: int, closest_neighbor: int) -> list[tuple[float, int]]: ...
