# Type stubs for centaur_technical_indicators.momentum_indicators
# Auto-generated from the Rust binding signatures; keep in sync with src/momentum_indicators.rs.

class single:
    @staticmethod
    def chaikin_oscillator(highs: list[float], lows: list[float], close: list[float], volume: list[float], short_period: int, previous_accumulation_distribution: float, short_period_model: str, long_period_model: str) -> tuple[float, float]: ...
    @staticmethod
    def chande_momentum_oscillator(prices: list[float]) -> float: ...
    @staticmethod
    def commodity_channel_index(prices: list[float], constant_model_type: str, deviation_model: str, constant_multiplier: float) -> float: ...
    @staticmethod
    def macd_line(prices: list[float], short_period: int, short_period_model: str, long_period_model: str) -> float: ...
    @staticmethod
    def mcginley_dynamic_commodity_channel_index(prices: list[float], previous_mcginley_dynamic: float, deviation_model: str, constant_multiplier: float) -> tuple[float, float]: ...
    @staticmethod
    def mcginley_dynamic_macd_line(prices: list[float], short_period: int, previous_short_mcginley: float, previous_long_mcginley: float) -> tuple[float, float, float]: ...
    @staticmethod
    def money_flow_index(prices: list[float], volume: list[float]) -> float: ...
    @staticmethod
    def on_balance_volume(current_price: float, previous_price: float, current_volume: float, previous_on_balance_volume: float) -> float: ...
    @staticmethod
    def percentage_price_oscillator(prices: list[float], short_period: int, constant_model_type: str) -> float: ...
    @staticmethod
    def rate_of_change(current_price: float, previous_price: float) -> float: ...
    @staticmethod
    def relative_strength_index(prices: list[float], constant_model_type: str) -> float: ...
    @staticmethod
    def signal_line(macds: list[float], constant_model_type: str) -> float: ...
    @staticmethod
    def slow_stochastic(stochastics: list[float], constant_model_type: str) -> float: ...
    @staticmethod
    def slowest_stochastic(slow_stochastics: list[float], constant_model_type: str) -> float: ...
    @staticmethod
    def stochastic_oscillator(prices: list[float]) -> float: ...
    @staticmethod
    def williams_percent_r(high: list[float], low: list[float], close: float) -> float: ...

class bulk:
    @staticmethod
    def chaikin_oscillator(highs: list[float], lows: list[float], close: list[float], volume: list[float], short_period: int, long_period: int, previous_accumulation_distribution: float, short_period_model: str, long_period_model: str) -> list[tuple[float, float]]: ...
    @staticmethod
    def chande_momentum_oscillator(prices: list[float], period: int) -> list[float]: ...
    @staticmethod
    def commodity_channel_index(prices: list[float], constant_model_type: str, deviation_model: str, constant_multiplier: float, period: int) -> list[float]: ...
    @staticmethod
    def macd_line(prices: list[float], short_period: int, short_period_model: str, long_period: int, long_period_model: str) -> list[float]: ...
    @staticmethod
    def mcginley_dynamic_commodity_channel_index(prices: list[float], previous_mcginley_dynamic: float, deviation_model: str, constant_multiplier: float, period: int) -> list[tuple[float, float]]: ...
    @staticmethod
    def mcginley_dynamic_macd_line(prices: list[float], short_period: int, previous_short_mcginley: float, long_period: int, previous_long_mcginley: float) -> list[tuple[float, float, float]]: ...
    @staticmethod
    def money_flow_index(prices: list[float], volume: list[float], period: int) -> list[float]: ...
    @staticmethod
    def on_balance_volume(prices: list[float], volume: list[float], previous_on_balance_volume: float) -> list[float]: ...
    @staticmethod
    def percentage_price_oscillator(prices: list[float], short_period: int, long_period: int, constant_model_type: str) -> list[float]: ...
    @staticmethod
    def rate_of_change(prices: list[float]) -> list[float]: ...
    @staticmethod
    def relative_strength_index(prices: list[float], constant_model_type: str, period: int) -> list[float]: ...
    @staticmethod
    def signal_line(macds: list[float], constant_model_type: str, period: int) -> list[float]: ...
    @staticmethod
    def slow_stochastic(stochastics: list[float], constant_model_type: str, period: int) -> list[float]: ...
    @staticmethod
    def slowest_stochastic(slow_stochastics: list[float], constant_model_type: str, period: int) -> list[float]: ...
    @staticmethod
    def stochastic_oscillator(prices: list[float], period: int) -> list[float]: ...
    @staticmethod
    def williams_percent_r(high: list[float], low: list[float], close: list[float], period: int) -> list[float]: ...

