# Type stubs for centaur_technical_indicators.other_indicators
# Auto-generated from the Rust binding signatures; keep in sync with src/other_indicators.rs.

class single:
    @staticmethod
    def average_true_range(close: list[float], high: list[float], low: list[float], constant_model_type: str) -> float: ...
    @staticmethod
    def internal_bar_strength(high: float, low: float, close: float) -> float: ...
    @staticmethod
    def return_on_investment(start_price: float, end_price: float, investment: float) -> tuple[float, float]: ...
    @staticmethod
    def true_range(close: float, high: float, low: float) -> float: ...

class bulk:
    @staticmethod
    def average_true_range(close: list[float], high: list[float], low: list[float], constant_model_type: str, period: int) -> list[float]: ...
    @staticmethod
    def internal_bar_strength(high: list[float], low: list[float], close: list[float]) -> list[float]: ...
    @staticmethod
    def positivity_indicator(open: list[float], previous_close: list[float], signal_period: int, constant_model_type: str) -> list[tuple[float, float]]: ...
    @staticmethod
    def return_on_investment(prices: list[float], investment: float) -> list[tuple[float, float]]: ...
    @staticmethod
    def true_range(close: list[float], high: list[float], low: list[float]) -> list[float]: ...

