# Type stubs for centaur_technical_indicators.strength_indicators
# Auto-generated from the Rust binding signatures; keep in sync with src/strength_indicators.rs.

class single:
    @staticmethod
    def accumulation_distribution(high: float, low: float, close: float, volume: float, previous_accumulation_distribution: float) -> float: ...
    @staticmethod
    def relative_vigor_index(open: list[float], high: list[float], low: list[float], close: list[float], constant_model_type: str) -> float: ...
    @staticmethod
    def volume_index(current_close: float, previous_close: float, previous_volume_index: float) -> float: ...

class bulk:
    @staticmethod
    def accumulation_distribution(highs: list[float], lows: list[float], close: list[float], volume: list[float], previous_accumulation_distribution: float) -> list[float]: ...
    @staticmethod
    def negative_volume_index(close: list[float], volume: list[float], previous_volume_index: float) -> list[float]: ...
    @staticmethod
    def positive_volume_index(close: list[float], volume: list[float], previous_volume_index: float) -> list[float]: ...
    @staticmethod
    def relative_vigor_index(open: list[float], high: list[float], low: list[float], close: list[float], constant_model_type: str, period: int) -> list[float]: ...

