# Type stubs for centaur_technical_indicators.trend_indicators
# Auto-generated from the Rust binding signatures; keep in sync with src/trend_indicators.rs.

class single:
    @staticmethod
    def aroon_down(lows: list[float]) -> float: ...
    @staticmethod
    def aroon_indicator(highs: list[float], lows: list[float]) -> tuple[float, float, float]: ...
    @staticmethod
    def aroon_oscillator(aroon_up: float, aroon_down: float) -> float: ...
    @staticmethod
    def aroon_up(highs: list[float]) -> float: ...
    @staticmethod
    def long_parabolic_time_price_system(previous_sar: float, extreme_point: float, af: float, low: float) -> float: ...
    @staticmethod
    def short_parabolic_time_price_system(previous_sar: float, extreme_point: float, af: float, high: float) -> float: ...
    @staticmethod
    def true_strength_index(prices: list[float], first_period: int, first_constant_model: str, second_constant_model: str) -> float: ...
    @staticmethod
    def volume_price_trend(current_price: float, previous_price: float, current_volume: float, previous_vpt: float) -> float: ...

class bulk:
    @staticmethod
    def aroon_down(lows: list[float], period: int) -> list[float]: ...
    @staticmethod
    def aroon_indicator(highs: list[float], lows: list[float], period: int) -> list[tuple[float, float, float]]: ...
    @staticmethod
    def aroon_oscillator(aroon_up: list[float], aroon_down: list[float]) -> list[float]: ...
    @staticmethod
    def aroon_up(highs: list[float], period: int) -> list[float]: ...
    @staticmethod
    def directional_movement_system(highs: list[float], lows: list[float], close: list[float], period: int, constant_model_type: str) -> list[tuple[float, float, float, float]]: ...
    @staticmethod
    def parabolic_time_price_system(highs: list[float], lows: list[float], af_start: float, af_step: float, af_max: float, position: str, previous_sar: float) -> list[float]: ...
    @staticmethod
    def true_strength_index(prices: list[float], first_constant_model: str, first_period: int, second_constant_model: str, second_period: int) -> list[float]: ...
    @staticmethod
    def volume_price_trend(prices: list[float], volumes: list[float], previous_vpt: float) -> list[float]: ...

